nathan/java/src/main/java/org/example/feb/뒤집기0220.java

```java
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
public class 뒤집기0220 {
public static void main(String[] args) throws IOException {
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String str = br.readLine();
char pre = str.charAt(0);
int one = 0;
int zero = 0;
if (pre == '1') {
one++;
} else {
zero++;
}
for (int i = 1; i < str.length(); i++) {
char ch = str.charAt(i);
if (pre != ch) {
if (ch == '1') {
one++;
} else {
zero++;
}
pre = ch;
}
}
System.out.print(Math.min(one, zero));
}
}
```
- 문자를 하나씩 탐색하며 0과 1이 바뀌는 순간에 one, zero 변수를 각각 +1 해주었습니다.
- 그 이후 one, zero 변수 중 최솟값을 반환했습니다.

20230220 뒤집기 풀이 완료

---

ron2/java/.gitignore
ron2/java/.idea/misc.xml
ron2/java/.idea/workspace.xml
ron2/java/src/main/java/org/example/feb/Boj20310.java

1은 앞에서부터, 0은 뒤에서부터 절반만 삭제하도록 했습니다.

[Ron2] 0221 타노스(BOJ20310) Java 풀이 

---

forkyy/python/feb/타노스.py

[첫번째 풀이]
- 조합 문제라고 생각해서 삭제 해야하는 개수만큼 0과 1을 제거하고 조합을 만들어서 정렬 후 반환하게 했음.
- 실패
[두번째 풀이]
- 그냥 0은 앞에서부터, 1은 뒤에서부터 제거했음
- 완료
- 시간 복잡도 : O(n * m)
- 공간 복잡도 : O() -> 모르겠음

[forkyy] 230221 타노스 python 풀이

---

forkyy/python/feb/연산자_끼워넣기.py

백트래킹 방식으로 모든 경우를 돌려버렸습니다.
각 연산을 하는 함수들을 하나의 배열로 만듬
함수에 현재 값과 인덱스를 넣어주고, 입력으로 받은 연산자의 개수가 남아있는 경우 연산을 했음.
- 시간 복잡도 : O(n^2)
- 공간 복잡도 : O()

[forkyy] 230222 연산자 끼워넣기 풀이 완료

---

donggi/java/src/main/java/org/example/feb/Boj14888.java

- 백트래킹으로 연산한 결과값이 최대일 때와 최소일 때를 갱신합니다
- 연산자는 차례대로 덧셈, 뺄셈, 곱셈, 나눗셈 순서대로 입력이 들어오기 때문에 반복문의 인덱스를 이용해 각 연산자의 연산 횟수를 차감해가며 연산을 진행합니다
- 공간 복잡도는 잘 모르겠네요

[donggi] 230222 연산자 끼워넣기 풀이 완료

---

minzino/java/src/main/java/org/example/feb/bj20310/Main.java

처음에는 입력된 0하고 1의 개수를 전부 2로 나누고 출력하면 되는 문제인 줄 알고 실패.
for문으로 입력된 0하고 1의 개수를 전부 2로 나눠 개수를 갖고있고, 
for문으로 문자열을 하나씩 확인하며 1일 경우 1의 개수만큼 빼고 그 다음부터 출력, 0일 경우 0의 개수만큼 출력 후 나머지는 출력하지 않음. 
- 공간 복잡도 : O(1)

[minzino] 230222 타노스 풀이 완료

---

nathan/.gitignore
nathan/java/.gitignore
nathan/java/.idea/sonarlint/issuestore/index.pb
nathan/java/.idea/workspace.xml
nathan/java/src/main/java/org/example/feb/연산자뒤집기0222.java
nathan/python/.gitignore
nathan/python/.idea/sonarlint/issuestore/index.pb
nathan/python/.idea/workspace.xml
nathan/python/feb/연산자끼워넣기0222.py
nathan/src/main/java/org/example/feb/fourth/java/문자열뒤집기.java

Link : https://www.acmicpc.net/problem/14888
- 연산자는 총 4개 있을 수 있습니다.
- 백트래킹을 돌릴 때 4개만큼 for문을 돌면서, 해당 연산자의 개수가 1 이상이라면, backtracking을 수행합니다.
- 단, 이 때, 연산 개수를 한 개 줄이고 backtracking을 호출한 뒤, 연산 개수를 다시 추가합니다.
- 이는 다른 연산자가 처음 오게 될 때, 개수가 남아있어야 정상적으로 경우의 수를 채울 수 있기 때문입니다.
- 시간 복잡도 : O(N!)

[nathan0222] 연산자 끼워넣기 java, python 풀이 완료

---

nathan/java/.idea/sonarlint/issuestore/index.pb
nathan/java/.idea/workspace.xml
nathan/java/src/main/java/org/example/feb/치킨배달0223.java
nathan/python/.idea/sonarlint/issuestore/index.pb
nathan/python/.idea/workspace.xml
nathan/python/feb/치킨배달0223.py

- 치킨 가게와 집의 좌표를 각각 리스트에 저장합니다.
- 치킨 가게들 중 M개를 선택하는 경우의 수를 백트래킹으로 탐색하여 저장합니다.
- 탐색된 치킨 가게의 조합들을 돌면서 집과의 거리를 구하고, 최솟값을 업데이트 합니다.
- 총 거리의 합을 구합니다.
- 시간 복잡도 : O(N * M!)

[nathan] 치킨배달 0223 java, python 풀이완료

---

forkyy/python/feb/치킨배달.py

combinations로 치킨집의 개수들의 조합을 만든 뒤, 3중 for문을 돌렸습니다.
- 시간 복잡도 : O(log n ^ 3)
- 공간 복잡도 : O()

[forkyy] 220223 치킨배달 풀이 완료

---

ron2/java/src/main/java/org/example/feb/Boj15686.java

조합을 실수해서 시간초과를 반복했습니다. 
3일뒤 다시 풀겠습니다.
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0223 Boj15686 치킨배달 자바 풀이

---

nathan/java/src/main/java/org/example/feb/용액0227.java
nathan/java/src/main/java/org/example/feb/용액0227_2.java

처음 풀이
- 양수와 음수 리스트를 나누어, 수가 많은 집단에 대해 이진 탐색으로 두 수의 차가 가장 작은 수를 구합니다.
- 이 방식으로 하는 경우 최악의 경우에는 O(NlogN)의 시간 복잡도가 걸립니다.
두번째 풀이
- 투 포인터를 활용하여 두 수의 합이 음수인 경우 start++, 양수인 경우 end--를 해주었고, 그 때마다 차를 비교하여 해를 업데이트 하였습니다.
- 이 방식으로 하는 경우 최악의 경우에는 O(N)의 시간 복잡도가 걸립니다.
- 공간 복잡도 : O()

[nathan] 용액 0227 재풀이 완료

---

nathan/java/src/main/java/org/example/feb/특정거리의도시찾기0228.java
nathan/python/feb/특정거리의도시찾기0228.py

- 출발 도시로부터 각 도시의 최단거리를 구했습니다.
- 우선 n개의 원소를 갖는 리스트를 모두 MAX_VALUE로 초기화 합니다.
- 출발지의 원소를 0으로 초기화 한 뒤, 연결된 노드들을 탐색하며 현재 위치에서 +1 한 값보다 원래 거리가 더 큰 경우에 현재위치+1의 값으로 업데이트 합니다.
- 모든 업데이트가 끝나면, 원소들을 돌며 k인 원소의 인덱스를 출력하고, 하나도 없다면 -1을 출력합니다.
- 공간 복잡도 : O(N)

[nathan] 특정거리의 도시찾기 0228 java, python 풀이 완 료

---

forkyy/python/feb/용액.py

투포인터로 풀었습니다.
기존 코드에서 정답값을 미리 설정해두지 않아서 문제가 발생하는것을 확인하고 다시 pr제출합니다.
- 시간 복잡도 : O(n)
- 공간 복잡도 : O()

[forkyy] 230227 용액 풀이 완료

---

forkyy/python/feb/특정_거리의_도시_찾기.py

bfs로 풀이했습니다.
- 시간 복잡도 : O(nlogn)
- 공간 복잡도 : O()

[forkyy] 230228 특정 거리의 도시 찾기 풀이 제출

---

forkyy/python/mar/zoac4.py

가로 세로 각각 앉을 수 있는 인원 수 구해서 곱했습니다.
- 시간 복잡도 : O(1)
- 공간 복잡도 : O()

[forkyy] 230301 zoac4 풀이 완료

---

nathan/java/src/main/java/org/example/mar/거짓말0302.java
nathan/python/codes/mar/거짓말0302.py

- python : union-find로 풀었습니다.
- java : 진실을 아는 집합에 한 명이라도 속한다면, 그 파티에 참석한 사람들은 모두 진실을 아는 집합에 속하게 됩니다. 이렇게 m번 수행하게 되면, 모든 파티에서 진실을 아는 파티와 진실을 알지 못하는 파티를 구분할 수 있게 됩니다.
- 시간 복잡도 : O(M^2) - java
- 공간 복잡도 : O()

[nathan] 거짓말 0302 python, java 풀이 완료

---

forkyy/python/mar/거짓말.py

union 메서드를 사용했습니다.
union find 알고리즘을 학습해서 내일모레 다시 풀어볼 예정입니다.
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[forkyy] 230302 거짓말 풀이 완료

---

ron2/java/src/main/java/org/example/mar/Boj2467.java

[Ron2]0306 Boj2467 용액 풀이

---

ron2/java/src/main/java/org/example/mar/Boj18352.java

BFS로 풀이했습니다.
최단거리가 K인 도시만 결과에 포함시켜야하는 지문을 정확하게 읽지 못해서, 삽질을 했습니다. 
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0307 Boj18352 특정 거리의 도시 찾기 풀이

---

ron2/java/src/main/java/org/example/mar/Boj1043Unionfind.java

유니온 파인드 개념을 배우고, 풀이했습니다.
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] BOj1043 유니온 파인드 풀이 완료

---

nathan/java/src/main/java/org/example/mar/가희와키워드0313.java

Hash 기반 컬렉션인 HashSet을 사용하여 탐색의 과정을 O(1)로 줄였습니다.
- 시간 복잡도 : O(M)
- 공간 복잡도 : O()

[nathan] 가희와 키워드 0313 java 풀이 완료

---

minzino/java/src/main/java/org/example/mar/bj2467/Main.java

투포인터를 이용하여 풀었습니다.
- 시간 복잡도 : O(n)
- 공간 복잡도 : O(n)

[minzino] bj2467 용액 풀이 완료

---

minzino/java/src/main/java/org/example/mar/bj18352/Main.java

주어진 출발점에서 다익스트라 알고리즘을 사용하여 최단 거리를 구한 뒤, 최단 거리가 K인 도시의 번호를 출력하였습니다.
- 시간 복잡도 : O(NlogN) 
- 공간 복잡도 : O(N)
시간 복잡도는 PriorityQueue를 사용해서 logN에 모든 노드를 검사하기때문에 N*logN으로 계산하였습니다.
bfs로도 풀 수 있을 것 같습니다.

[minzino] bj18352 특정 거리의 도시 찾기 풀이 완료

---

minzino/java/src/main/java/org/example/mar/bj23971/Main.java

참가자들이 앉을 수 있는 위치를 계산하기 위해 다음과 같이 공식을 사용했습니다.
height = (H - 1) / (N + 1) + 1
width = (W - 1) / (M + 1) + 1
각 행과 열에서 참가자가 앉을 수 있는 위치의 개수를 구하는 공식입니다. 
- 시간 복잡도 : O(1)
- 공간 복잡도 : O(1)

[minzino] bj23971 ZOAC4 - 수학

---

ron2/java/src/main/java/org/example/mar/Boj11404.java
ron2/java/src/main/java/org/example/mar/Boj1389.java
ron2/java/src/main/java/org/example/mar/바이러스검사.java
ron2/java/src/main/java/org/example/mar/카드짝맞추기.java

[Ron2] 0324 카드짝맞추기 실패, 플로이드 성공

---

ron2/java/src/main/java/org/example/mar/Boj6087.java

방향정보에 대해서 visit를 체크하는 풀이
우선순위큐를 사용했는데, 그렇게하면 기본 visit cost만으로도 풀이할수있을것같기도....
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0324 BOJ6087 레이저 통신 풀이

---

nathan/java/src/main/java/org/example/mar/플로이드0326.java

플로이드 워셜 알고리즘 활용
3중 포문을 통해 풀이
(맨 첫 번째 for문은 중간 지점을 의미한다.)
- 시간 복잡도 : O(N^3)
- 공간 복잡도 : O()

[nathan] 0326 플로이드 java 풀이 완료

---

ron2/java/src/main/java/org/example/mar/Boj2310.java

DFS
메모리 초과가 나게 코드를 짜서 몇번 삽질을 했습니다. 
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0331 BOJ 2310 풀이 완료

---

ron2/java/src/main/java/org/example/apr/Boj17182.java
ron2/java/src/main/java/org/example/mar/Boj24337.java

가희와 탑 - 그리디 (풀이실패)
우주탐사선 - 플로이드 와샬 + 백트랙킹
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0402 우주 탐사선 풀이 완료, 가희와 탑 풀이 실패

---

ron2/java/src/main/java/org/example/apr/Boj10159.java

- 플로이드와샬 응용문제입니다.
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0412 BOJ10159 저울 풀이 완료

---

ron2/java/src/main/java/org/example/apr/Boj2109.java
ron2/java/src/main/java/org/example/apr/Programmers_이모티콘할인행사.java

그리디 및 완탐 풀이 연습
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0414 BOJ2109 및 프로그래머스 이모티콘할인행사 풀이 완료

---

ron2/java/src/main/java/org/example/apr/Programmers_연속펄스부분수열의합.java
ron2/java/src/main/java/org/example/apr/Programmers_이모티콘할인행사.java
ron2/java/src/main/java/org/example/apr/Programmers_인사고과.java

[Ron2] 0427 프로그래머스 solve

---

ron2/java/src/main/java/org/example/apr/Boj1197.java
ron2/java/src/main/java/org/example/apr/Programmers_택배배달수거하기.java
ron2/java/src/main/java/org/example/apr/Programmers_표현가능한이진트리.java

[Ron2] 0428 풀이

---

ron2/java/src/main/java/org/example/apr/Boj13335.java
ron2/java/src/main/java/org/example/apr/Boj21921.java

[Ron2] 0429 백준 택배, 블로그 풀이완료

---

ron2/java/src/main/java/org/example/apr/Boj11501.java
ron2/java/src/main/java/org/example/apr/Boj16234.java
ron2/java/src/main/java/org/example/apr/Boj2668.java
ron2/java/src/main/java/org/example/apr/Boj4179.java

[Ron2] 0430 백준 문제 풀이 완료

---

ron2/java/src/main/java/org/example/may/Boj18405.java
ron2/java/src/main/java/org/example/may/Boj18428.java

[Ron2] 0501 경쟁적 전염, 감시피하기 풀이 완료

---

ron2/java/src/main/java/org/example/may/Boj13418.java
ron2/java/src/main/java/org/example/may/Boj2056.java

최소 스패닝 트리, 위상정렬 
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0501 백준 문제 풀이 완료

---

ron2/java/src/main/java/org/example/may/Boj1446.java
ron2/java/src/main/java/org/example/may/Boj20920.java
ron2/java/src/main/java/org/example/may/Boj2174.java

지름길, 영단어 암기는 괴로워, 로봇 시뮬레이션
- 시간 복잡도 : O()
- 공간 복잡도 : O()

[Ron2] 0502 백준 풀이 완료
